name: soad_project
description: An ERP (Enterprise Resource Planning) project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  clipboard_manager: ^0.0.4
  scoped_model: ^1.0.1
  shared_preferences: '^0.5.1+2'
  rxdart: '^0.21.0'
  http: ^0.12.0+2
  url_launcher: ^5.1.2
  chewie: ^0.9.7
  flutter_markdown: ^0.2.0
  fancy_bottom_navigation: ^0.3.2
  carousel_slider: ^1.3.0
  transparent_image: ^1.0.0
  percent_indicator: ^2.1.1+1
  flutter_calendar_carousel: ^1.4.2
  flutter_pagewise: 1.2.3
  flutter_plugin_pdf_viewer: 1.0.7
  flutter_email_sender: 2.1.0
  string_validator: 0.1.3
  flutter_launcher_icons: ^0.7.4
  charts_flutter: ^0.8.1








dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  image_path: 'assets/images/logo.png'
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/finance/finance_growth_projection.jpeg
    - assets/images/finance/finance_manage.jpg
    - assets/images/finance/finance_statement.jpg
    - assets/images/finance/finance_tracking1.jpg
    - assets/images/complain.png
    - assets/images/complain-box.png

  # example:
  fonts:
      - family: UbuntuMono
        fonts:
          - asset: fonts/UbuntuMono-Regular.ttf

      - family: Roboto
        fonts:
          - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
